project:
  type: website
  output-dir: docs

website:
  title: "AI x R meetup ðŸ¤–"
  reader-mode: true
  repo-url: https://github.com/ai-r-meetup/AIxR
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: meetings.qmd
        text: Meet
      - href: discussion.qmd
        text: Discuss
      - href: additional-resources.qmd
        text: Educational Resources

    tools:
      - icon: github
        href: https://github.com/ai-r-meetup/AIxR
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Gina Reynolds, Kyle?, Hadley?"

format:
  html:
    theme: theme.scss
    toc: true

editor: source
